<a href="https://colab.research.google.com/github/Shivamtripathi13/python/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


The Basics

In [ ]:
a = np.array([1,2,3])
print(a)


[1 2 3]


In [ ]:
b = np.array([[10,4.4,11],[33,44,33]])
print(b)

[[10.   4.4 11. ]
 [33.  44.  33. ]]


In [ ]:
#get dimension
a.ndim

1

In [ ]:
#get dimension for b
b.ndim

2

In [ ]:
#get shape
a.shape

(3,)

In [ ]:
#get shape for b
b.shape

(2, 3)

In [ ]:
#get type
a.dtype

dtype('int64')

In [ ]:
#get size
b.itemsize


8

In [ ]:
#get total size
a.size

3

Accessing/Changing Specific Elements, Rows, Columns

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[2,5,4,33,5,7,8]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 2  5  4 33  5  7  8]]


In [ ]:
#get size
a.shape

(2, 7)

Initializing Different Arrays

In [ ]:
#all 0's matrix
np.zeros((2,3,3,))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#all 1s matrix
np.ones((1,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
#any other number
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [ ]:
#random decimal numbers
np.random.rand(4,2,3)

array([[[0.22209474, 0.28831172, 0.99451613],
        [0.47988475, 0.56549904, 0.04710405]],

       [[0.49026991, 0.22849907, 0.25682336],
        [0.10726483, 0.92544303, 0.95858657]],

       [[0.62169518, 0.12362668, 0.89750056],
        [0.08541278, 0.77803315, 0.17250518]],

       [[0.62570892, 0.22287626, 0.6299677 ],
        [0.85242402, 0.0543246 , 0.66027592]]])

In [ ]:
#random integer values
np.random.randint(2,3)

2

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying variables!

In [ ]:
a = np.array([1,2,3])
b=a

b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [ ]:
a = np.array([1,2,3])
b= a.copy()
b[0] = 100
print(a)

[1 2 3]


 Basic Mathematics

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a+ 2

array([3, 4, 5, 6, 7])

In [ ]:
 a - 2

array([-1,  0,  1,  2,  3])

In [ ]:
b = np.array([2,3,4,1,1])
a + b

array([3, 5, 7, 5, 6])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [ ]:
#vertically stacking variables
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])